CREATE TABLE ADLOGIN_TBL
(
USERNAME VARCHAR(30) NOT NULL,
PASS NVARCHAR(30) NOT NULL

);
SELECT * FROM ADLOGIN_TBL;

INSERT INTO ADLOGIN_TBL VALUES ('tamim@gmail.com','123'); 
INSERT INTO ADLOGIN_TBL VALUES ('prottoy@gmail.com','456'); 
INSERT INTO ADLOGIN_TBL VALUES ('shojib@gmail.com','789'); 
INSERT INTO ADLOGIN_TBL VALUES ('mahim@gmail.com','963'); 
