CREATE TABLE addSTUDENT
(
SL NVARCHAR (60) NOT NULL,
USERNAME VARCHAR (60) NOT NULL,
PASS NVARCHAR (60) NOT NULL,
ID NVARCHAR (60) NOT NULL,
DEPARTMENT VARCHAR (60) NOT NULL,
);

SELECT *FROM addSTUDENT