CREATE TABLE addBook
(
BOOK_SL INT NOT NULL Primary key, 
BOOKNAME VARCHAR(50) NOT NULL,
WRITER VARCHAR(50) NOT NULL,
CATEGORY VARCHAR(50) NOT NULL,
QUANTITY VARCHAR(50) NOT NULL,
PRICE VARCHAR(50) NOT NULL,


)